# This file was generated by GoReleaser. DO NOT EDIT.
cask "engram-custom" do
  name "engram-custom"
  desc "Engram (ClaroDrive fork): persistent memory for AI coding agents, with engram-projects"
  homepage "https://github.com/HoracioEspinosa/engram"
  version "1.20.0-cd.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "engram"

  on_macos do
    on_intel do
      url "https://github.com/HoracioEspinosa/engram/releases/download/v#{version}/engram_#{version}_darwin_amd64.tar.gz"
      sha256 "723920276974baa6636ee2f69f4c992ce72451b6e97f19d22145d1ad8cc1d559"
    end
    on_arm do
      url "https://github.com/HoracioEspinosa/engram/releases/download/v#{version}/engram_#{version}_darwin_arm64.tar.gz"
      sha256 "2dda8c91f2ec595a5370fc55283e302e0d6933032f24edd3f3100fd963e7a3c7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/HoracioEspinosa/engram/releases/download/v#{version}/engram_#{version}_linux_amd64.tar.gz"
      sha256 "3a2245a908dd901898679622b8caed73fa4c99199382d6cf3bb195af56bb5e96"
    end
    on_arm do
      url "https://github.com/HoracioEspinosa/engram/releases/download/v#{version}/engram_#{version}_linux_arm64.tar.gz"
      sha256 "cf321c0c29ac5333425140bd711085425fcbaf675252efac30c9ee829a9ff335"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/engram"]
    end
  end

  caveats do
    "This build replaces the upstream engram binary. If Homebrew refuses to"
    "link it, uninstall the upstream formula first:"
    ""
    "  brew uninstall engram"
    ""
    "After installing, confirm the version and the schema:"
    ""
    "  engram --version"
    "  engram doctor"
  end

  # No zap stanza required
end
