# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EngramCustom < Formula
  desc "Engram (ClaroDrive fork): persistent memory for AI coding agents, with engram-projects"
  homepage "https://github.com/HoracioEspinosa/engram"
  version "1.20.0-cd.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HoracioEspinosa/engram/releases/download/v1.20.0-cd.9/engram_1.20.0-cd.9_darwin_amd64.tar.gz"
      sha256 "8be10863b878972f25154b82674b916d2c970def8a377c51101ac6405033400b"

      def install
        bin.install "engram"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HoracioEspinosa/engram/releases/download/v1.20.0-cd.9/engram_1.20.0-cd.9_darwin_arm64.tar.gz"
      sha256 "735d21fe1a6de652c3344fa3180ef9b617d618824f5c1912b8411ecbc450a97b"

      def install
        bin.install "engram"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/HoracioEspinosa/engram/releases/download/v1.20.0-cd.9/engram_1.20.0-cd.9_linux_amd64.tar.gz"
      sha256 "b25c481055b8537be18a5fb996fe4de2f7c28e843009f30bc20ffbcca1ecc1fc"
      def install
        bin.install "engram"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HoracioEspinosa/engram/releases/download/v1.20.0-cd.9/engram_1.20.0-cd.9_linux_arm64.tar.gz"
      sha256 "ddd66d235712fb263fc9d46111e6a59c848ef3e00e7e3c4eb8ce9a57db0c2402"
      def install
        bin.install "engram"
      end
    end
  end

  def caveats
    <<~EOS
      This build replaces the upstream engram binary. If Homebrew refuses to
      link it, uninstall the upstream formula first:

        brew uninstall engram

      After installing, confirm the version and the schema:

        engram --version
        engram doctor
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/engram --version")
  end
end
