# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EngramCustom < Formula
  desc "Engram (ClaroDrive fork): persistent memory for AI coding agents, with engram-projects"
  homepage "https://github.com/HoracioEspinosa/engram"
  version "1.20.0-cd.14"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HoracioEspinosa/engram/releases/download/v1.20.0-cd.14/engram_1.20.0-cd.14_darwin_amd64.tar.gz"
      sha256 "01bc4b0cee916de4713cbce2903491d0eae2408b600cf905f6cf7954609f33b5"

      def install
        bin.install "engram"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HoracioEspinosa/engram/releases/download/v1.20.0-cd.14/engram_1.20.0-cd.14_darwin_arm64.tar.gz"
      sha256 "d3cfe468ca55c93d6092afddf507105717e36af5f5164b070147a933744506e1"

      def install
        bin.install "engram"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/HoracioEspinosa/engram/releases/download/v1.20.0-cd.14/engram_1.20.0-cd.14_linux_amd64.tar.gz"
      sha256 "e0b095ce23eace8d4d04bcc97253cd55e81a8eeec6a548421a0ce9758635faa6"
      def install
        bin.install "engram"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HoracioEspinosa/engram/releases/download/v1.20.0-cd.14/engram_1.20.0-cd.14_linux_arm64.tar.gz"
      sha256 "06ce01180a34b3d360fceb09af8d1d43e3cde0ab3b62d02fdcdb7e332ca4b37b"
      def install
        bin.install "engram"
      end
    end
  end

  def caveats
    <<~EOS
      This build replaces the upstream engram binary. If Homebrew refuses to
      link it, uninstall the upstream formula first:

        brew uninstall engram

      After installing, confirm the version and the schema:

        engram --version
        engram doctor
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/engram --version")
  end
end
