# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EngramCustom < Formula
  desc "Engram (ClaroDrive fork): persistent memory for AI coding agents, with engram-projects"
  homepage "https://github.com/HoracioEspinosa/engram"
  version "1.20.0-cd.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/HoracioEspinosa/engram/releases/download/v1.20.0-cd.11/engram_1.20.0-cd.11_darwin_amd64.tar.gz"
      sha256 "627303c4036c106f0bb8c600ddec82b17778d4c82f1dcecabf18119ab0ac220c"

      def install
        bin.install "engram"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/HoracioEspinosa/engram/releases/download/v1.20.0-cd.11/engram_1.20.0-cd.11_darwin_arm64.tar.gz"
      sha256 "962c95c0fb3870e5d4e589193721b9d11f0f99078da11bc95480ef950f33fe43"

      def install
        bin.install "engram"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/HoracioEspinosa/engram/releases/download/v1.20.0-cd.11/engram_1.20.0-cd.11_linux_amd64.tar.gz"
      sha256 "3a7230dde40cbc61f7824eec9e1481200dd64f2dbee863d0d8c817e7060b22b4"
      def install
        bin.install "engram"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/HoracioEspinosa/engram/releases/download/v1.20.0-cd.11/engram_1.20.0-cd.11_linux_arm64.tar.gz"
      sha256 "e0b29d9bc39c41a9a66496db94f6944cdd2ca8da915f8e762f0e938aad0eab3d"
      def install
        bin.install "engram"
      end
    end
  end

  def caveats
    <<~EOS
      This build replaces the upstream engram binary. If Homebrew refuses to
      link it, uninstall the upstream formula first:

        brew uninstall engram

      After installing, confirm the version and the schema:

        engram --version
        engram doctor
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/engram --version")
  end
end
