# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Memory < Formula
  desc "Persistent memory for AI coding agents. Agent-agnostic, single binary, zero dependencies."
  homepage "https://github.com/HoracioEspinosa/memory"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/horacioespinosa/memory/releases/download/v1.0.3/memory_1.0.3_darwin_amd64.tar.gz"
      sha256 "f855bbc28153b5aea99ee69bdde575f29199dae03c7caee3e413afbd9fac97f7"

      def install
        bin.install "memory"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/horacioespinosa/memory/releases/download/v1.0.3/memory_1.0.3_darwin_arm64.tar.gz"
      sha256 "7885142b24ab706aef98b63f75bde4245a108aa87577323032f551eafb294d1f"

      def install
        bin.install "memory"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/horacioespinosa/memory/releases/download/v1.0.3/memory_1.0.3_linux_amd64.tar.gz"
      sha256 "aa5e57bcac984e9db049726cab4b9178c31dec921659ee520320738fabe0a711"
      def install
        bin.install "memory"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/horacioespinosa/memory/releases/download/v1.0.3/memory_1.0.3_linux_arm64.tar.gz"
      sha256 "1018eddf7d3873077fd146d31464e85723130a16318cf12fbd8037dd0a7190ff"
      def install
        bin.install "memory"
      end
    end
  end

  conflicts_with "memory-custom"

  test do
    assert_match version.to_s, shell_output("#{bin}/memory --version")
  end
end
