# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Memory < Formula
  desc "Persistent memory for AI coding agents. Agent-agnostic, single binary, zero dependencies."
  homepage "https://github.com/HoracioEspinosa/memory"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/horacioespinosa/memory/releases/download/v1.0.1/memory_1.0.1_darwin_amd64.tar.gz"
      sha256 "6ffbd1e4d18862d5d51b5837f6d58e45df588abcf885c9bd588b78cdb386f062"

      def install
        bin.install "memory"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/horacioespinosa/memory/releases/download/v1.0.1/memory_1.0.1_darwin_arm64.tar.gz"
      sha256 "e43c03bb36647aa126c15fc10bc20380259e0b381ab5e6cd91f46adaab0ebe66"

      def install
        bin.install "memory"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/horacioespinosa/memory/releases/download/v1.0.1/memory_1.0.1_linux_amd64.tar.gz"
      sha256 "587a96ecd4d1048812826914385223dee27650ee9e5aaee502925d66ceec626b"
      def install
        bin.install "memory"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/horacioespinosa/memory/releases/download/v1.0.1/memory_1.0.1_linux_arm64.tar.gz"
      sha256 "b83e110bf76f9e799899e70b9ac3b56716c14dc55424f2584165baf4f106d95c"
      def install
        bin.install "memory"
      end
    end
  end

  conflicts_with "memory-custom"

  test do
    assert_match version.to_s, shell_output("#{bin}/memory --version")
  end
end
